# choices.py

SCHOOL_CHOICES = [
    ('SDO', 'Division Office'),
    ('Agban NHS', 'Agban NHS'),
    ('Antipolo NHS', 'Antipolo NHS'),
    ('Bagamanoc RDHS', 'Bagamanoc RDHS'),
    ('Baldoc IS', 'Baldoc Integrated School'),
    ('Baras RDHS', 'Baras RDHS'),
    ('Bato RDHS', 'Bato RDHS'),
    ('Bote IS', 'Bote Integrated School'),
    ('Bugao NHS', 'Bugao NHS'),
    ('Buyo IHS', 'Buyo Integrated H/S'),
    ('Cabcab NHS', 'Cabcab NHS'),
    ('Cabugao IS', 'Cabugao Integrated School'),
    ('Calatagan HS', 'Calatagan HS'),
    ('Caramoran RDHS', 'Caramoran RDHS'),
    ('Caramoran SF', 'Caramoran SF'),
    ('CNHS', 'Catanduanes National High School (CNHS)'),
    ('Cobo IS', 'Cobo Integrated School'),
    ('Codon NHS', 'Codon NHS'),
    ('Dariao NHS', 'Dariao NHS'),
    ('Dororian NHS', 'Dororian NHS'),
    ('Gigmoto RDHS', 'Gigmoto RDHS'),
    ('Hawan NHS', 'Hawan NHS'),
    ('LIVSNHS', 'Leandro I. Verceles Sr. NHS'),
    ('Lictin IS', 'Lictin Integrated School'),
    ('Magnesia NHS', 'Magnesia NHS'),
    ('Manambrag NHS', 'Manambrag NHS'),
    ('Mayngaway NHS', 'Mayngaway NHS'),
    ('Milaviga IS', 'Milaviga Integrated School'),
    ('Obi ES', 'Obi Elementary School'),
    ('Pagsangahan IS', 'Pagsangahan Integrated School'),
    ('Palta NHS', 'Palta NHS'),
    ('Palumbanes IS', 'Palumbanes Integrated School'),
    ('PSAT', 'Pandan Sch. Of Arts & Trades'),
    ('Panganiban NHS', 'Panganiban NHS'),
    ('Panganiban NHS-CAIC', 'Panganiban NHS, CAIC Compound'),
    ('SAVS', 'San Andres Vocational School'),
    ('San Jose NHS', 'San Jose NHS'),
    ('San Miguel RDHS', 'San Miguel RDHS'),
    ('San Miguel RDHS-Mabato', 'San Miguel RDHS-Annex (Mabato HS)'),
    ('San Vicente NHS', 'San Vicente NHS'),
    ('Sicmil IHS', 'Sicmil Int. H.S.'),
    ('Supang-Datag NHS', 'Supang-Datag NHS'),
    ('Tambongon NHS', 'Tambongon NHS'),
    ('Tinago NHS', 'Tinago NHS'),
    ('Tubli NHS', 'Tubli NHS'),
    ('Tucao-Maysuram IS', 'Tucao-Maysuram Integrated School'),
    ('Viga RDHS', 'Viga RDHS'),
]

GENDER_CHOICES = [
    ('Male', 'Male'),
    ('Female', 'Female'),
]