# Generated by Django 5.0.4 on 2026-03-07 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_options_alter_school_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
