# Generated by Django 5.0.4 on 2026-03-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_email',
            field=models.EmailField(default='', help_text='Notifications for approval will be sent here.', max_length=255, verbose_name='Personal Gmail Address'),
            preserve_default=False,
        ),
    ]
