# Generated by Django 4.2.19 on 2026-03-13 08:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_user_personal_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-date_uploaded'], 'verbose_name': 'Document/Memo'},
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?63[0-9]{10}$', 'Enter valid PH mobile number (+639xxxxxxxxx)')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='personal_email',
            field=models.EmailField(blank=True, help_text='Notifications for approval will be sent here.', max_length=255, null=True, verbose_name='Personal Gmail Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ReceivedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='documents.document')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_memos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Received Document',
                'verbose_name_plural': 'Received Documents',
                'ordering': ['-date_received'],
            },
        ),
    ]
