# Generated by Django 4.2.19 on 2026-03-16 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_document_options_alter_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('word', 'Word Document'), ('excel', 'Excel Spreadsheet'), ('ppt', 'PowerPoint Presentation'), ('pdf', 'PDF File')], default='pdf', max_length=10),
        ),
        migrations.AddField(
            model_name='receiveddocument',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_memos', to=settings.AUTH_USER_MODEL),
        ),
    ]
